run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gosec
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - exhaustive
    - gocritic
    - noctx
    - sqlclosecheck
    - rowserrcheck

linters-settings:
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 5
